--------------------------------------------------------
--  File created - Saturday-December-02-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ASSIGNED_NURSE
--------------------------------------------------------

  CREATE TABLE "ASSIGNED_NURSE" 
   (	"EMPLOYEEID" VARCHAR2(20 BYTE), 
	"TYPEOFNURSE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DBCOURSE" ;
REM INSERTING into ASSIGNED_NURSE
SET DEFINE OFF;
Insert into ASSIGNED_NURSE (EMPLOYEEID,TYPEOFNURSE) values ('EMP006','ICU Nurse');
Insert into ASSIGNED_NURSE (EMPLOYEEID,TYPEOFNURSE) values ('EMP007','Pediatric Nurse');
Insert into ASSIGNED_NURSE (EMPLOYEEID,TYPEOFNURSE) values ('EMP008','Operating Room Nurse');
Insert into ASSIGNED_NURSE (EMPLOYEEID,TYPEOFNURSE) values ('EMP009','Emergency Room Nurse');
Insert into ASSIGNED_NURSE (EMPLOYEEID,TYPEOFNURSE) values ('EMP010','Gynocology Nurse');
Insert into ASSIGNED_NURSE (EMPLOYEEID,TYPEOFNURSE) values ('EMP016','Gynocology Nurse');
--------------------------------------------------------
--  DDL for Index SYS_C001840579
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C001840579" ON "ASSIGNED_NURSE" ("EMPLOYEEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DBCOURSE" ;
--------------------------------------------------------
--  Constraints for Table ASSIGNED_NURSE
--------------------------------------------------------

  ALTER TABLE "ASSIGNED_NURSE" ADD PRIMARY KEY ("EMPLOYEEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DBCOURSE"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ASSIGNED_NURSE
--------------------------------------------------------

  ALTER TABLE "ASSIGNED_NURSE" ADD CONSTRAINT "ASSIGNED_NURSE_FK1" FOREIGN KEY ("EMPLOYEEID")
	  REFERENCES "STAFF" ("EMPLOYEEID") ENABLE;
