--------------------------------------------------------
--  File created - Saturday-December-02-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table COVERAGE_DETAILS
--------------------------------------------------------

  CREATE TABLE "COVERAGE_DETAILS" 
   (	"COVERAGETYPE" VARCHAR2(35 BYTE), 
	"COPAYAMOUNT" NUMBER(10,2), 
	"POLICYINCLUSIONSTATUS" VARCHAR2(30 BYTE), 
	"INSURANCENUMBER" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DBCOURSE" ;
REM INSERTING into COVERAGE_DETAILS
SET DEFINE OFF;
Insert into COVERAGE_DETAILS (COVERAGETYPE,COPAYAMOUNT,POLICYINCLUSIONSTATUS,INSURANCENUMBER) values ('Basic Hospital Plan',3000,'Included','IN123456');
Insert into COVERAGE_DETAILS (COVERAGETYPE,COPAYAMOUNT,POLICYINCLUSIONSTATUS,INSURANCENUMBER) values ('Basic Hospital Plan',2500,'Included','IN789012');
Insert into COVERAGE_DETAILS (COVERAGETYPE,COPAYAMOUNT,POLICYINCLUSIONSTATUS,INSURANCENUMBER) values ('Light Hospital Plan',6000,'Included','IN345678');
Insert into COVERAGE_DETAILS (COVERAGETYPE,COPAYAMOUNT,POLICYINCLUSIONSTATUS,INSURANCENUMBER) values ('Light Hospital Plan',8000,'Included','IN567890');
Insert into COVERAGE_DETAILS (COVERAGETYPE,COPAYAMOUNT,POLICYINCLUSIONSTATUS,INSURANCENUMBER) values ('Hospital Plus',25000,'Included','IN901234');
Insert into COVERAGE_DETAILS (COVERAGETYPE,COPAYAMOUNT,POLICYINCLUSIONSTATUS,INSURANCENUMBER) values ('Hospital Plus',28000,'Included','IN234567');
Insert into COVERAGE_DETAILS (COVERAGETYPE,COPAYAMOUNT,POLICYINCLUSIONSTATUS,INSURANCENUMBER) values ('Basic Hospital Plan',3500,'Included','IN890123');
Insert into COVERAGE_DETAILS (COVERAGETYPE,COPAYAMOUNT,POLICYINCLUSIONSTATUS,INSURANCENUMBER) values ('Basic Hospital Plan',4000,'Included','IN456789');
Insert into COVERAGE_DETAILS (COVERAGETYPE,COPAYAMOUNT,POLICYINCLUSIONSTATUS,INSURANCENUMBER) values ('Light Hospital Plan',9000,'Included','IN012345');
Insert into COVERAGE_DETAILS (COVERAGETYPE,COPAYAMOUNT,POLICYINCLUSIONSTATUS,INSURANCENUMBER) values ('Light Hospital Plan',7000,'Included','IN678901');
Insert into COVERAGE_DETAILS (COVERAGETYPE,COPAYAMOUNT,POLICYINCLUSIONSTATUS,INSURANCENUMBER) values ('Hospital Plus',24000,'Included','IN678111');
Insert into COVERAGE_DETAILS (COVERAGETYPE,COPAYAMOUNT,POLICYINCLUSIONSTATUS,INSURANCENUMBER) values ('Basic Hospital Plan',3200,'Included','IN111111');
Insert into COVERAGE_DETAILS (COVERAGETYPE,COPAYAMOUNT,POLICYINCLUSIONSTATUS,INSURANCENUMBER) values ('Basic Hospital Plan',2800,'Included','IN222222');
Insert into COVERAGE_DETAILS (COVERAGETYPE,COPAYAMOUNT,POLICYINCLUSIONSTATUS,INSURANCENUMBER) values ('Light Hospital Plan',7000,'Included','IN333333');
Insert into COVERAGE_DETAILS (COVERAGETYPE,COPAYAMOUNT,POLICYINCLUSIONSTATUS,INSURANCENUMBER) values ('Light Hospital Plan',8500,'Included','IN444444');
Insert into COVERAGE_DETAILS (COVERAGETYPE,COPAYAMOUNT,POLICYINCLUSIONSTATUS,INSURANCENUMBER) values ('Hospital Plus',29000,'Included','IN555555');
Insert into COVERAGE_DETAILS (COVERAGETYPE,COPAYAMOUNT,POLICYINCLUSIONSTATUS,INSURANCENUMBER) values ('Hospital Plus',27000,'Included','IN666666');
Insert into COVERAGE_DETAILS (COVERAGETYPE,COPAYAMOUNT,POLICYINCLUSIONSTATUS,INSURANCENUMBER) values ('Basic Hospital Plan',3800,'Included','IN777777');
Insert into COVERAGE_DETAILS (COVERAGETYPE,COPAYAMOUNT,POLICYINCLUSIONSTATUS,INSURANCENUMBER) values ('Basic Hospital Plan',3100,'Included','IN888888');
Insert into COVERAGE_DETAILS (COVERAGETYPE,COPAYAMOUNT,POLICYINCLUSIONSTATUS,INSURANCENUMBER) values ('Light Hospital Plan',8000,'Included','IN999999');
Insert into COVERAGE_DETAILS (COVERAGETYPE,COPAYAMOUNT,POLICYINCLUSIONSTATUS,INSURANCENUMBER) values ('Light Hospital Plan',9500,'Included','IN101010');
Insert into COVERAGE_DETAILS (COVERAGETYPE,COPAYAMOUNT,POLICYINCLUSIONSTATUS,INSURANCENUMBER) values ('Hospital Plus',23000,'Included','IN1111110');
Insert into COVERAGE_DETAILS (COVERAGETYPE,COPAYAMOUNT,POLICYINCLUSIONSTATUS,INSURANCENUMBER) values ('Hospital Plus',26000,'Included','IN1212121');
Insert into COVERAGE_DETAILS (COVERAGETYPE,COPAYAMOUNT,POLICYINCLUSIONSTATUS,INSURANCENUMBER) values ('Basic Hospital Plan',2900,'Included','IN1313131');
Insert into COVERAGE_DETAILS (COVERAGETYPE,COPAYAMOUNT,POLICYINCLUSIONSTATUS,INSURANCENUMBER) values ('Basic Hospital Plan',3400,'Included','IN123000');
Insert into COVERAGE_DETAILS (COVERAGETYPE,COPAYAMOUNT,POLICYINCLUSIONSTATUS,INSURANCENUMBER) values ('Light Hospital Plan',7500,'Included','IN789111');
Insert into COVERAGE_DETAILS (COVERAGETYPE,COPAYAMOUNT,POLICYINCLUSIONSTATUS,INSURANCENUMBER) values ('Light Hospital Plan',8500,'Included','IN345222');
Insert into COVERAGE_DETAILS (COVERAGETYPE,COPAYAMOUNT,POLICYINCLUSIONSTATUS,INSURANCENUMBER) values ('Hospital Plus',22000,'Included','IN901333');
Insert into COVERAGE_DETAILS (COVERAGETYPE,COPAYAMOUNT,POLICYINCLUSIONSTATUS,INSURANCENUMBER) values ('Hospital Plus',27000,'Included','IN567444');
Insert into COVERAGE_DETAILS (COVERAGETYPE,COPAYAMOUNT,POLICYINCLUSIONSTATUS,INSURANCENUMBER) values ('Basic Hospital Plan',3600,'Included','IN234555');
Insert into COVERAGE_DETAILS (COVERAGETYPE,COPAYAMOUNT,POLICYINCLUSIONSTATUS,INSURANCENUMBER) values ('Basic Hospital Plan',3000,'Included','IN890666');
Insert into COVERAGE_DETAILS (COVERAGETYPE,COPAYAMOUNT,POLICYINCLUSIONSTATUS,INSURANCENUMBER) values ('Light Hospital Plan',7000,'Included','IN456777');
Insert into COVERAGE_DETAILS (COVERAGETYPE,COPAYAMOUNT,POLICYINCLUSIONSTATUS,INSURANCENUMBER) values ('Light Hospital Plan',9500,'Included','IN012888');
Insert into COVERAGE_DETAILS (COVERAGETYPE,COPAYAMOUNT,POLICYINCLUSIONSTATUS,INSURANCENUMBER) values ('Hospital Plus',26000,'Included','IN678999');
Insert into COVERAGE_DETAILS (COVERAGETYPE,COPAYAMOUNT,POLICYINCLUSIONSTATUS,INSURANCENUMBER) values ('Hospital Plus',29000,'Included','IN6781010');
Insert into COVERAGE_DETAILS (COVERAGETYPE,COPAYAMOUNT,POLICYINCLUSIONSTATUS,INSURANCENUMBER) values ('Basic Hospital Plan',3300,'Included','IN1111112');
Insert into COVERAGE_DETAILS (COVERAGETYPE,COPAYAMOUNT,POLICYINCLUSIONSTATUS,INSURANCENUMBER) values ('Basic Hospital Plan',2900,'Included','IN1212123');
Insert into COVERAGE_DETAILS (COVERAGETYPE,COPAYAMOUNT,POLICYINCLUSIONSTATUS,INSURANCENUMBER) values ('Light Hospital Plan',8000,'Included','IN1313134');
Insert into COVERAGE_DETAILS (COVERAGETYPE,COPAYAMOUNT,POLICYINCLUSIONSTATUS,INSURANCENUMBER) values ('Light Hospital Plan',7500,'Included','IN9362135');
--------------------------------------------------------
--  DDL for Index SYS_C001840595
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C001840595" ON "COVERAGE_DETAILS" ("COVERAGETYPE", "INSURANCENUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DBCOURSE" ;
--------------------------------------------------------
--  Constraints for Table COVERAGE_DETAILS
--------------------------------------------------------

  ALTER TABLE "COVERAGE_DETAILS" ADD PRIMARY KEY ("COVERAGETYPE", "INSURANCENUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DBCOURSE"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COVERAGE_DETAILS
--------------------------------------------------------

  ALTER TABLE "COVERAGE_DETAILS" ADD CONSTRAINT "COVERAGE_DETAILS_FK1" FOREIGN KEY ("INSURANCENUMBER")
	  REFERENCES "INSURANCE" ("INSURANCENUMBER") ENABLE;
