--------------------------------------------------------
--  File created - Saturday-December-02-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table HEALTH_RECORD
--------------------------------------------------------

  CREATE TABLE "HEALTH_RECORD" 
   (	"HEALTHRECORDID" VARCHAR2(15 BYTE), 
	"ORGANDONOR" VARCHAR2(5 BYTE), 
	"HEALTHCARDNUMBER" VARCHAR2(15 BYTE), 
	"VITALINFO" VARCHAR2(29 BYTE), 
	"IMMUNIZATIONRECORD" VARCHAR2(35 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DBCOURSE" ;
REM INSERTING into HEALTH_RECORD
SET DEFINE OFF;
Insert into HEALTH_RECORD (HEALTHRECORDID,ORGANDONOR,HEALTHCARDNUMBER,VITALINFO,IMMUNIZATIONRECORD) values ('HR123456','No','HC123456','Stable, BP: 120/80, HR: 70','Up to date');
Insert into HEALTH_RECORD (HEALTHRECORDID,ORGANDONOR,HEALTHCARDNUMBER,VITALINFO,IMMUNIZATIONRECORD) values ('HR789012','Yes','HC789012','Stable, BP: 118/76, HR: 72','Up to date');
Insert into HEALTH_RECORD (HEALTHRECORDID,ORGANDONOR,HEALTHCARDNUMBER,VITALINFO,IMMUNIZATIONRECORD) values ('HR345678','No','HC345678','Stable, BP: 122/78, HR: 75','Up to date');
Insert into HEALTH_RECORD (HEALTHRECORDID,ORGANDONOR,HEALTHCARDNUMBER,VITALINFO,IMMUNIZATIONRECORD) values ('HR901234','Yes','HC901234','Stable, BP: 124/80, HR: 68','Up to date');
Insert into HEALTH_RECORD (HEALTHRECORDID,ORGANDONOR,HEALTHCARDNUMBER,VITALINFO,IMMUNIZATIONRECORD) values ('HR567890','No','HC567890','Stable, BP: 120/82, HR: 74','Up to date');
Insert into HEALTH_RECORD (HEALTHRECORDID,ORGANDONOR,HEALTHCARDNUMBER,VITALINFO,IMMUNIZATIONRECORD) values ('HR234567','No','HC234567','Stable, BP: 126/78, HR: 70','Up to date');
Insert into HEALTH_RECORD (HEALTHRECORDID,ORGANDONOR,HEALTHCARDNUMBER,VITALINFO,IMMUNIZATIONRECORD) values ('HR890123','Yes','HC890123','Stable, BP: 118/76, HR: 72','Up to date');
Insert into HEALTH_RECORD (HEALTHRECORDID,ORGANDONOR,HEALTHCARDNUMBER,VITALINFO,IMMUNIZATIONRECORD) values ('HR456789','No','HC456789','Stable, BP: 124/80, HR: 75','Up to date');
Insert into HEALTH_RECORD (HEALTHRECORDID,ORGANDONOR,HEALTHCARDNUMBER,VITALINFO,IMMUNIZATIONRECORD) values ('HR012345','Yes','HC012345','Stable, BP: 122/78, HR: 70','Up to date');
Insert into HEALTH_RECORD (HEALTHRECORDID,ORGANDONOR,HEALTHCARDNUMBER,VITALINFO,IMMUNIZATIONRECORD) values ('HR678901','No','HC678901','Stable, BP: 120/82, HR: 68','Up to date');
Insert into HEALTH_RECORD (HEALTHRECORDID,ORGANDONOR,HEALTHCARDNUMBER,VITALINFO,IMMUNIZATIONRECORD) values ('HR678111','No','HC678111','Stable, BP: 126/78, HR: 72','Up to date');
Insert into HEALTH_RECORD (HEALTHRECORDID,ORGANDONOR,HEALTHCARDNUMBER,VITALINFO,IMMUNIZATIONRECORD) values ('HR111111','Yes','HC111111','Stable, BP: 118/76, HR: 75','Up to date');
Insert into HEALTH_RECORD (HEALTHRECORDID,ORGANDONOR,HEALTHCARDNUMBER,VITALINFO,IMMUNIZATIONRECORD) values ('HR222222','No','HC222222','Stable, BP: 124/80, HR: 74','Up to date');
Insert into HEALTH_RECORD (HEALTHRECORDID,ORGANDONOR,HEALTHCARDNUMBER,VITALINFO,IMMUNIZATIONRECORD) values ('HR333333','No','HC333333','Stable, BP: 122/78, HR: 70','Up to date');
Insert into HEALTH_RECORD (HEALTHRECORDID,ORGANDONOR,HEALTHCARDNUMBER,VITALINFO,IMMUNIZATIONRECORD) values ('HR444444','Yes','HC444444','Stable, BP: 120/82, HR: 72','Up to date');
Insert into HEALTH_RECORD (HEALTHRECORDID,ORGANDONOR,HEALTHCARDNUMBER,VITALINFO,IMMUNIZATIONRECORD) values ('HR555555','No','HC555555','Stable, BP: 126/78, HR: 68','Up to date');
Insert into HEALTH_RECORD (HEALTHRECORDID,ORGANDONOR,HEALTHCARDNUMBER,VITALINFO,IMMUNIZATIONRECORD) values ('HR666666','No','HC666666','Stable, BP: 118/76, HR: 70','Up to date');
Insert into HEALTH_RECORD (HEALTHRECORDID,ORGANDONOR,HEALTHCARDNUMBER,VITALINFO,IMMUNIZATIONRECORD) values ('HR777777','Yes','HC777777','Unstable, BP: 124/80, HR: 75','Up to date');
Insert into HEALTH_RECORD (HEALTHRECORDID,ORGANDONOR,HEALTHCARDNUMBER,VITALINFO,IMMUNIZATIONRECORD) values ('HR888888','No','HC888888','Stable, BP: 122/78, HR: 74','Up to date');
Insert into HEALTH_RECORD (HEALTHRECORDID,ORGANDONOR,HEALTHCARDNUMBER,VITALINFO,IMMUNIZATIONRECORD) values ('HR999999','No','HC999999','Stable, BP: 120/82, HR: 70','Up to date');
Insert into HEALTH_RECORD (HEALTHRECORDID,ORGANDONOR,HEALTHCARDNUMBER,VITALINFO,IMMUNIZATIONRECORD) values ('HR101010','Yes','HC101010','Stable, BP: 126/78, HR: 72','Up to date');
Insert into HEALTH_RECORD (HEALTHRECORDID,ORGANDONOR,HEALTHCARDNUMBER,VITALINFO,IMMUNIZATIONRECORD) values ('HR1111110','No','HC1111110','Stable, BP: 118/76, HR: 68','Up to date');
Insert into HEALTH_RECORD (HEALTHRECORDID,ORGANDONOR,HEALTHCARDNUMBER,VITALINFO,IMMUNIZATIONRECORD) values ('HR1212121','No','HC1212121','Stable, BP: 124/80, HR: 70','Up to date');
Insert into HEALTH_RECORD (HEALTHRECORDID,ORGANDONOR,HEALTHCARDNUMBER,VITALINFO,IMMUNIZATIONRECORD) values ('HR1313131','No','HC1313131','Stable, BP: 120/80, HR: 70','Up to date');
Insert into HEALTH_RECORD (HEALTHRECORDID,ORGANDONOR,HEALTHCARDNUMBER,VITALINFO,IMMUNIZATIONRECORD) values ('HR1414141','No','HC9362136','Unstable, BP: 190/40, HR: 70','Up to date');
Insert into HEALTH_RECORD (HEALTHRECORDID,ORGANDONOR,HEALTHCARDNUMBER,VITALINFO,IMMUNIZATIONRECORD) values ('HR1515151','No','HC6969696','Unstable, BP: 160/100, HR: 70','Up to date');
Insert into HEALTH_RECORD (HEALTHRECORDID,ORGANDONOR,HEALTHCARDNUMBER,VITALINFO,IMMUNIZATIONRECORD) values ('HR123000','No','HC123000','Stable, BP: 128/78, HR: 75','Up to date');
Insert into HEALTH_RECORD (HEALTHRECORDID,ORGANDONOR,HEALTHCARDNUMBER,VITALINFO,IMMUNIZATIONRECORD) values ('HR789111','Yes','HC789111','Stable, BP: 122/82, HR: 74','Up to date');
Insert into HEALTH_RECORD (HEALTHRECORDID,ORGANDONOR,HEALTHCARDNUMBER,VITALINFO,IMMUNIZATIONRECORD) values ('HR345222','No','HC345222','Stable, BP: 126/78, HR: 70','Up to date');
Insert into HEALTH_RECORD (HEALTHRECORDID,ORGANDONOR,HEALTHCARDNUMBER,VITALINFO,IMMUNIZATIONRECORD) values ('HR901333','Yes','HC901333','Stable, BP: 118/76, HR: 72','Up to date');
Insert into HEALTH_RECORD (HEALTHRECORDID,ORGANDONOR,HEALTHCARDNUMBER,VITALINFO,IMMUNIZATIONRECORD) values ('HR567444','No','HC567444','Stable, BP: 124/80, HR: 75','Up to date');
Insert into HEALTH_RECORD (HEALTHRECORDID,ORGANDONOR,HEALTHCARDNUMBER,VITALINFO,IMMUNIZATIONRECORD) values ('HR234555','No','HC234555','Stable, BP: 122/78, HR: 70','Up to date');
Insert into HEALTH_RECORD (HEALTHRECORDID,ORGANDONOR,HEALTHCARDNUMBER,VITALINFO,IMMUNIZATIONRECORD) values ('HR890666','Yes','HC890666','Stable, BP: 120/82, HR: 74','Up to date');
Insert into HEALTH_RECORD (HEALTHRECORDID,ORGANDONOR,HEALTHCARDNUMBER,VITALINFO,IMMUNIZATIONRECORD) values ('HR456777','No','HC456777','Stable, BP: 126/78, HR: 68','Up to date');
Insert into HEALTH_RECORD (HEALTHRECORDID,ORGANDONOR,HEALTHCARDNUMBER,VITALINFO,IMMUNIZATIONRECORD) values ('HR012888','No','HC012888','Stable, BP: 118/76, HR: 70','Up to date');
Insert into HEALTH_RECORD (HEALTHRECORDID,ORGANDONOR,HEALTHCARDNUMBER,VITALINFO,IMMUNIZATIONRECORD) values ('HR678999','Yes','HC678999','Stable, BP: 124/80, HR: 74','Up to date');
Insert into HEALTH_RECORD (HEALTHRECORDID,ORGANDONOR,HEALTHCARDNUMBER,VITALINFO,IMMUNIZATIONRECORD) values ('HR6781010','No','HC6781010','Stable, BP: 122/78, HR: 70','Up to date');
Insert into HEALTH_RECORD (HEALTHRECORDID,ORGANDONOR,HEALTHCARDNUMBER,VITALINFO,IMMUNIZATIONRECORD) values ('HR1111112','No','HC1111112','Stable, BP: 126/78, HR: 68','Up to date');
Insert into HEALTH_RECORD (HEALTHRECORDID,ORGANDONOR,HEALTHCARDNUMBER,VITALINFO,IMMUNIZATIONRECORD) values ('HR1212123','Yes','HC1212123','Stable, BP: 118/76, HR: 70','Up to date');
Insert into HEALTH_RECORD (HEALTHRECORDID,ORGANDONOR,HEALTHCARDNUMBER,VITALINFO,IMMUNIZATIONRECORD) values ('HR1313134','No','HC1313134','Stable, BP: 124/80, HR: 75','Up to date');
Insert into HEALTH_RECORD (HEALTHRECORDID,ORGANDONOR,HEALTHCARDNUMBER,VITALINFO,IMMUNIZATIONRECORD) values ('HR9362135','No','HC9362135','Stable, BP: 122/78, HR: 70','Not up to date');
--------------------------------------------------------
--  DDL for Index SYS_C001840585
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C001840585" ON "HEALTH_RECORD" ("HEALTHRECORDID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DBCOURSE" ;
--------------------------------------------------------
--  Constraints for Table HEALTH_RECORD
--------------------------------------------------------

  ALTER TABLE "HEALTH_RECORD" ADD PRIMARY KEY ("HEALTHRECORDID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DBCOURSE"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table HEALTH_RECORD
--------------------------------------------------------

  ALTER TABLE "HEALTH_RECORD" ADD CONSTRAINT "HEALTH_RECORD_FK1" FOREIGN KEY ("HEALTHCARDNUMBER")
	  REFERENCES "PATIENT" ("HEALTHCARDNUMBER") ENABLE;
