--------------------------------------------------------
--  File created - Saturday-December-02-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table HOSPITAL
--------------------------------------------------------

  CREATE TABLE "HOSPITAL" 
   (	"HOSPITALID" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(24 BYTE), 
	"CITY" VARCHAR2(100 BYTE), 
	"STREET" VARCHAR2(35 BYTE), 
	"POSTALCODE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DBCOURSE" ;
REM INSERTING into HOSPITAL
SET DEFINE OFF;
Insert into HOSPITAL (HOSPITALID,NAME,CITY,STREET,POSTALCODE) values ('B2C3E4g5','Toronto General Hospital','Toronto','200 Elizabeth St','M5G 2C4');
--------------------------------------------------------
--  DDL for Index SYS_C001840574
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C001840574" ON "HOSPITAL" ("HOSPITALID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DBCOURSE" ;
--------------------------------------------------------
--  Constraints for Table HOSPITAL
--------------------------------------------------------

  ALTER TABLE "HOSPITAL" ADD PRIMARY KEY ("HOSPITALID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DBCOURSE"  ENABLE;
