--------------------------------------------------------
--  File created - Saturday-December-02-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table INSURANCE
--------------------------------------------------------

  CREATE TABLE "INSURANCE" 
   (	"INSURANCENUMBER" VARCHAR2(20 BYTE), 
	"INSURANCEPROVIDER" VARCHAR2(25 BYTE), 
	"HEALTHCARDNUMBER" VARCHAR2(15 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DBCOURSE" ;
REM INSERTING into INSURANCE
SET DEFINE OFF;
Insert into INSURANCE (INSURANCENUMBER,INSURANCEPROVIDER,HEALTHCARDNUMBER) values ('IN123456','Government Insurance','HC123456');
Insert into INSURANCE (INSURANCENUMBER,INSURANCEPROVIDER,HEALTHCARDNUMBER) values ('IN789012','PrivateCare Insurance','HC789012');
Insert into INSURANCE (INSURANCENUMBER,INSURANCEPROVIDER,HEALTHCARDNUMBER) values ('IN345678','MediShield Insurance','HC345678');
Insert into INSURANCE (INSURANCENUMBER,INSURANCEPROVIDER,HEALTHCARDNUMBER) values ('IN567890','SecureHealth Insurance','HC567890');
Insert into INSURANCE (INSURANCENUMBER,INSURANCEPROVIDER,HEALTHCARDNUMBER) values ('IN901234','Government Insurance','HC901234');
Insert into INSURANCE (INSURANCENUMBER,INSURANCEPROVIDER,HEALTHCARDNUMBER) values ('IN234567','MediGuard Insurance','HC234567');
Insert into INSURANCE (INSURANCENUMBER,INSURANCEPROVIDER,HEALTHCARDNUMBER) values ('IN890123','PrivateCare Insurance','HC890123');
Insert into INSURANCE (INSURANCENUMBER,INSURANCEPROVIDER,HEALTHCARDNUMBER) values ('IN456789','HealthGuard Insurance','HC456789');
Insert into INSURANCE (INSURANCENUMBER,INSURANCEPROVIDER,HEALTHCARDNUMBER) values ('IN012345','SecureHealth Insurance','HC012345');
Insert into INSURANCE (INSURANCENUMBER,INSURANCEPROVIDER,HEALTHCARDNUMBER) values ('IN678901','Government Insurance','HC678901');
Insert into INSURANCE (INSURANCENUMBER,INSURANCEPROVIDER,HEALTHCARDNUMBER) values ('IN678111','MediShield Insurance','HC678111');
Insert into INSURANCE (INSURANCENUMBER,INSURANCEPROVIDER,HEALTHCARDNUMBER) values ('IN111111','PrivateCare Insurance','HC111111');
Insert into INSURANCE (INSURANCENUMBER,INSURANCEPROVIDER,HEALTHCARDNUMBER) values ('IN222222','SecureHealth Insurance','HC222222');
Insert into INSURANCE (INSURANCENUMBER,INSURANCEPROVIDER,HEALTHCARDNUMBER) values ('IN333333','Government Insurance','HC333333');
Insert into INSURANCE (INSURANCENUMBER,INSURANCEPROVIDER,HEALTHCARDNUMBER) values ('IN444444','MediGuard Insurance','HC444444');
Insert into INSURANCE (INSURANCENUMBER,INSURANCEPROVIDER,HEALTHCARDNUMBER) values ('IN555555','PrivateCare Insurance','HC555555');
Insert into INSURANCE (INSURANCENUMBER,INSURANCEPROVIDER,HEALTHCARDNUMBER) values ('IN666666','HealthGuard Insurance','HC666666');
Insert into INSURANCE (INSURANCENUMBER,INSURANCEPROVIDER,HEALTHCARDNUMBER) values ('IN777777','MediShield Insurance','HC777777');
Insert into INSURANCE (INSURANCENUMBER,INSURANCEPROVIDER,HEALTHCARDNUMBER) values ('IN888888','Government Insurance','HC888888');
Insert into INSURANCE (INSURANCENUMBER,INSURANCEPROVIDER,HEALTHCARDNUMBER) values ('IN999999','SecureHealth Insurance','HC999999');
Insert into INSURANCE (INSURANCENUMBER,INSURANCEPROVIDER,HEALTHCARDNUMBER) values ('IN101010','MediGuard Insurance','HC101010');
Insert into INSURANCE (INSURANCENUMBER,INSURANCEPROVIDER,HEALTHCARDNUMBER) values ('IN1111110','PrivateCare Insurance','HC1111110');
Insert into INSURANCE (INSURANCENUMBER,INSURANCEPROVIDER,HEALTHCARDNUMBER) values ('IN1212121','HealthGuard Insurance','HC1212121');
Insert into INSURANCE (INSURANCENUMBER,INSURANCEPROVIDER,HEALTHCARDNUMBER) values ('IN1313131','MediShield Insurance','HC1313131');
Insert into INSURANCE (INSURANCENUMBER,INSURANCEPROVIDER,HEALTHCARDNUMBER) values ('IN123000','Government Insurance','HC123000');
Insert into INSURANCE (INSURANCENUMBER,INSURANCEPROVIDER,HEALTHCARDNUMBER) values ('IN789111','PrivateCare Insurance','HC789111');
Insert into INSURANCE (INSURANCENUMBER,INSURANCEPROVIDER,HEALTHCARDNUMBER) values ('IN345222','SecureHealth Insurance','HC345222');
Insert into INSURANCE (INSURANCENUMBER,INSURANCEPROVIDER,HEALTHCARDNUMBER) values ('IN901333','Government Insurance','HC901333');
Insert into INSURANCE (INSURANCENUMBER,INSURANCEPROVIDER,HEALTHCARDNUMBER) values ('IN567444','MediGuard Insurance','HC567444');
Insert into INSURANCE (INSURANCENUMBER,INSURANCEPROVIDER,HEALTHCARDNUMBER) values ('IN234555','PrivateCare Insurance','HC234555');
Insert into INSURANCE (INSURANCENUMBER,INSURANCEPROVIDER,HEALTHCARDNUMBER) values ('IN890666','HealthGuard Insurance','HC890666');
Insert into INSURANCE (INSURANCENUMBER,INSURANCEPROVIDER,HEALTHCARDNUMBER) values ('IN456777','MediShield Insurance','HC456777');
Insert into INSURANCE (INSURANCENUMBER,INSURANCEPROVIDER,HEALTHCARDNUMBER) values ('IN012888','Government Insurance','HC012888');
Insert into INSURANCE (INSURANCENUMBER,INSURANCEPROVIDER,HEALTHCARDNUMBER) values ('IN678999','SecureHealth Insurance','HC678999');
Insert into INSURANCE (INSURANCENUMBER,INSURANCEPROVIDER,HEALTHCARDNUMBER) values ('IN6781010','MediGuard Insurance','HC6781010');
Insert into INSURANCE (INSURANCENUMBER,INSURANCEPROVIDER,HEALTHCARDNUMBER) values ('IN1111112','PrivateCare Insurance','HC1111112');
Insert into INSURANCE (INSURANCENUMBER,INSURANCEPROVIDER,HEALTHCARDNUMBER) values ('IN1212123','HealthGuard Insurance','HC1212123');
Insert into INSURANCE (INSURANCENUMBER,INSURANCEPROVIDER,HEALTHCARDNUMBER) values ('IN1313134','MediShield Insurance','HC1313134');
Insert into INSURANCE (INSURANCENUMBER,INSURANCEPROVIDER,HEALTHCARDNUMBER) values ('IN9362135','Government Insurance','HC9362135');
--------------------------------------------------------
--  DDL for Index SYS_C001840587
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C001840587" ON "INSURANCE" ("INSURANCENUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DBCOURSE" ;
--------------------------------------------------------
--  Constraints for Table INSURANCE
--------------------------------------------------------

  ALTER TABLE "INSURANCE" ADD PRIMARY KEY ("INSURANCENUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DBCOURSE"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table INSURANCE
--------------------------------------------------------

  ALTER TABLE "INSURANCE" ADD CONSTRAINT "INSURANCE_FK1" FOREIGN KEY ("HEALTHCARDNUMBER")
	  REFERENCES "PATIENT" ("HEALTHCARDNUMBER") ENABLE;
