--------------------------------------------------------
--  File created - Saturday-December-02-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MEDICATIONS
--------------------------------------------------------

  CREATE TABLE "MEDICATIONS" 
   (	"MEDICATIONID" VARCHAR2(25 BYTE), 
	"DOSAGE" VARCHAR2(20 BYTE), 
	"BRAND" VARCHAR2(100 BYTE), 
	"SIDEEFFECTS" VARCHAR2(20 BYTE), 
	"HEALTHRECORDID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DBCOURSE" ;
REM INSERTING into MEDICATIONS
SET DEFINE OFF;
Insert into MEDICATIONS (MEDICATIONID,DOSAGE,BRAND,SIDEEFFECTS,HEALTHRECORDID) values ('MD121212','55mg','MediWell','Dizziness, Insomnia','HR123456');
Insert into MEDICATIONS (MEDICATIONID,DOSAGE,BRAND,SIDEEFFECTS,HEALTHRECORDID) values ('MD131313','70mg','PharmaCare','Headache, Fatigue','HR789012');
Insert into MEDICATIONS (MEDICATIONID,DOSAGE,BRAND,SIDEEFFECTS,HEALTHRECORDID) values ('MD141414','10mg','MediCare','Nausea, Dizziness','HR345678');
Insert into MEDICATIONS (MEDICATIONID,DOSAGE,BRAND,SIDEEFFECTS,HEALTHRECORDID) values ('MD151515','20mg','PharmaHealth','Dry Mouth, Insomnia','HR901234');
Insert into MEDICATIONS (MEDICATIONID,DOSAGE,BRAND,SIDEEFFECTS,HEALTHRECORDID) values ('MD161616','15mg','MediWell','Nausea, Drowsiness','HR567890');
Insert into MEDICATIONS (MEDICATIONID,DOSAGE,BRAND,SIDEEFFECTS,HEALTHRECORDID) values ('MD171717','25mg','PharmaCare','Dizziness, Fatigue','HR234567');
Insert into MEDICATIONS (MEDICATIONID,DOSAGE,BRAND,SIDEEFFECTS,HEALTHRECORDID) values ('MD181818','30mg','MediCare','Dry Mouth, Insomnia','HR890123');
Insert into MEDICATIONS (MEDICATIONID,DOSAGE,BRAND,SIDEEFFECTS,HEALTHRECORDID) values ('MD191919','40mg','PharmaHealth','Nausea, Drowsiness','HR456789');
Insert into MEDICATIONS (MEDICATIONID,DOSAGE,BRAND,SIDEEFFECTS,HEALTHRECORDID) values ('MD202020','35mg','MediWell','Headache, Dizziness','HR012345');
Insert into MEDICATIONS (MEDICATIONID,DOSAGE,BRAND,SIDEEFFECTS,HEALTHRECORDID) values ('MD212121','45mg','PharmaCare','Nausea, Fatigue','HR678901');
Insert into MEDICATIONS (MEDICATIONID,DOSAGE,BRAND,SIDEEFFECTS,HEALTHRECORDID) values ('MD242424','15mg','MediSafe','Nausea, Dizziness','HR123000');
Insert into MEDICATIONS (MEDICATIONID,DOSAGE,BRAND,SIDEEFFECTS,HEALTHRECORDID) values ('MD252525','30mg','PharmaSafe','Dry Mouth, Insomnia','HR789111');
Insert into MEDICATIONS (MEDICATIONID,DOSAGE,BRAND,SIDEEFFECTS,HEALTHRECORDID) values ('MD262626','25mg','MediGuard','Nausea, Drowsiness','HR345222');
Insert into MEDICATIONS (MEDICATIONID,DOSAGE,BRAND,SIDEEFFECTS,HEALTHRECORDID) values ('MD272727','40mg','PharmaGuard','Dizziness, Fatigue','HR901333');
Insert into MEDICATIONS (MEDICATIONID,DOSAGE,BRAND,SIDEEFFECTS,HEALTHRECORDID) values ('MD282828','20mg','MediSafe','Dry Mouth, Insomnia','HR567444');
Insert into MEDICATIONS (MEDICATIONID,DOSAGE,BRAND,SIDEEFFECTS,HEALTHRECORDID) values ('MD292929','55mg','PharmaSafe','Nausea, Drowsiness','HR234555');
Insert into MEDICATIONS (MEDICATIONID,DOSAGE,BRAND,SIDEEFFECTS,HEALTHRECORDID) values ('MD303030','60mg','MediGuard','Headache, Dizziness','HR890666');
Insert into MEDICATIONS (MEDICATIONID,DOSAGE,BRAND,SIDEEFFECTS,HEALTHRECORDID) values ('MD313131','35mg','PharmaGuard','Nausea, Fatigue','HR456777');
--------------------------------------------------------
--  DDL for Index SYS_C001840591
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C001840591" ON "MEDICATIONS" ("MEDICATIONID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DBCOURSE" ;
--------------------------------------------------------
--  Constraints for Table MEDICATIONS
--------------------------------------------------------

  ALTER TABLE "MEDICATIONS" ADD PRIMARY KEY ("MEDICATIONID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DBCOURSE"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MEDICATIONS
--------------------------------------------------------

  ALTER TABLE "MEDICATIONS" ADD CONSTRAINT "MEDICATIONS_FK1" FOREIGN KEY ("HEALTHRECORDID")
	  REFERENCES "HEALTH_RECORD" ("HEALTHRECORDID") ENABLE;
