--------------------------------------------------------
--  File created - Saturday-December-02-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for View PATIENTS_HEALTH_RECORDS
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "PATIENTS_HEALTH_RECORDS" ("FIRSTNAME", "LASTNAME", "HEALTHCARDNUMBER", "VITALINFO") AS 
  SELECT
    p.FIRSTNAME,
    p.LASTNAME,
    p.HEALTHCARDNUMBER,
    hr.VITALINFO
FROM 
    PATIENT p
INNER JOIN 
    HEALTH_RECORD hr
ON
    p.HEALTHCARDNUMBER = hr.HEALTHCARDNUMBER
;
REM INSERTING into PATIENTS_HEALTH_RECORDS
SET DEFINE OFF;
Insert into PATIENTS_HEALTH_RECORDS (FIRSTNAME,LASTNAME,HEALTHCARDNUMBER,VITALINFO) values ('John','Doe','HC123456','Stable, BP: 120/80, HR: 70');
Insert into PATIENTS_HEALTH_RECORDS (FIRSTNAME,LASTNAME,HEALTHCARDNUMBER,VITALINFO) values ('Jane','Smith','HC789012','Stable, BP: 118/76, HR: 72');
Insert into PATIENTS_HEALTH_RECORDS (FIRSTNAME,LASTNAME,HEALTHCARDNUMBER,VITALINFO) values ('Michael','Johnson','HC345678','Stable, BP: 122/78, HR: 75');
Insert into PATIENTS_HEALTH_RECORDS (FIRSTNAME,LASTNAME,HEALTHCARDNUMBER,VITALINFO) values ('Sarah','Williams','HC901234','Stable, BP: 124/80, HR: 68');
Insert into PATIENTS_HEALTH_RECORDS (FIRSTNAME,LASTNAME,HEALTHCARDNUMBER,VITALINFO) values ('David','Brown','HC567890','Stable, BP: 120/82, HR: 74');
Insert into PATIENTS_HEALTH_RECORDS (FIRSTNAME,LASTNAME,HEALTHCARDNUMBER,VITALINFO) values ('Emily','Taylor','HC234567','Stable, BP: 126/78, HR: 70');
Insert into PATIENTS_HEALTH_RECORDS (FIRSTNAME,LASTNAME,HEALTHCARDNUMBER,VITALINFO) values ('James','Miller','HC890123','Stable, BP: 118/76, HR: 72');
Insert into PATIENTS_HEALTH_RECORDS (FIRSTNAME,LASTNAME,HEALTHCARDNUMBER,VITALINFO) values ('Olivia','Anderson','HC456789','Stable, BP: 124/80, HR: 75');
Insert into PATIENTS_HEALTH_RECORDS (FIRSTNAME,LASTNAME,HEALTHCARDNUMBER,VITALINFO) values ('Daniel','Davis','HC012345','Stable, BP: 122/78, HR: 70');
Insert into PATIENTS_HEALTH_RECORDS (FIRSTNAME,LASTNAME,HEALTHCARDNUMBER,VITALINFO) values ('Ava','Clark','HC678901','Stable, BP: 120/82, HR: 68');
Insert into PATIENTS_HEALTH_RECORDS (FIRSTNAME,LASTNAME,HEALTHCARDNUMBER,VITALINFO) values ('Ahraz','Kibria','HC678111','Stable, BP: 126/78, HR: 72');
Insert into PATIENTS_HEALTH_RECORDS (FIRSTNAME,LASTNAME,HEALTHCARDNUMBER,VITALINFO) values ('Isabella','Johnson','HC111111','Stable, BP: 118/76, HR: 75');
Insert into PATIENTS_HEALTH_RECORDS (FIRSTNAME,LASTNAME,HEALTHCARDNUMBER,VITALINFO) values ('Ethan','Smith','HC222222','Stable, BP: 124/80, HR: 74');
Insert into PATIENTS_HEALTH_RECORDS (FIRSTNAME,LASTNAME,HEALTHCARDNUMBER,VITALINFO) values ('Olivia','Anderson','HC333333','Stable, BP: 122/78, HR: 70');
Insert into PATIENTS_HEALTH_RECORDS (FIRSTNAME,LASTNAME,HEALTHCARDNUMBER,VITALINFO) values ('Liam','Williams','HC444444','Stable, BP: 120/82, HR: 72');
Insert into PATIENTS_HEALTH_RECORDS (FIRSTNAME,LASTNAME,HEALTHCARDNUMBER,VITALINFO) values ('Ava','Jones','HC555555','Stable, BP: 126/78, HR: 68');
Insert into PATIENTS_HEALTH_RECORDS (FIRSTNAME,LASTNAME,HEALTHCARDNUMBER,VITALINFO) values ('Noah','Davis','HC666666','Stable, BP: 118/76, HR: 70');
Insert into PATIENTS_HEALTH_RECORDS (FIRSTNAME,LASTNAME,HEALTHCARDNUMBER,VITALINFO) values ('Sophia','Miller','HC777777','Unstable, BP: 124/80, HR: 75');
Insert into PATIENTS_HEALTH_RECORDS (FIRSTNAME,LASTNAME,HEALTHCARDNUMBER,VITALINFO) values ('Logan','Taylor','HC888888','Stable, BP: 122/78, HR: 74');
Insert into PATIENTS_HEALTH_RECORDS (FIRSTNAME,LASTNAME,HEALTHCARDNUMBER,VITALINFO) values ('Mia','Brown','HC999999','Stable, BP: 120/82, HR: 70');
Insert into PATIENTS_HEALTH_RECORDS (FIRSTNAME,LASTNAME,HEALTHCARDNUMBER,VITALINFO) values ('Charlotte','Evans','HC101010','Stable, BP: 126/78, HR: 72');
Insert into PATIENTS_HEALTH_RECORDS (FIRSTNAME,LASTNAME,HEALTHCARDNUMBER,VITALINFO) values ('Oliver','Hill','HC1111110','Stable, BP: 118/76, HR: 68');
Insert into PATIENTS_HEALTH_RECORDS (FIRSTNAME,LASTNAME,HEALTHCARDNUMBER,VITALINFO) values ('Amelia','Clark','HC1212121','Stable, BP: 124/80, HR: 70');
Insert into PATIENTS_HEALTH_RECORDS (FIRSTNAME,LASTNAME,HEALTHCARDNUMBER,VITALINFO) values ('Harper','Martin','HC1313131','Stable, BP: 120/80, HR: 70');
Insert into PATIENTS_HEALTH_RECORDS (FIRSTNAME,LASTNAME,HEALTHCARDNUMBER,VITALINFO) values ('Sarah','Khan','HC9362136','Unstable, BP: 190/40, HR: 70');
Insert into PATIENTS_HEALTH_RECORDS (FIRSTNAME,LASTNAME,HEALTHCARDNUMBER,VITALINFO) values ('Taha','Ghori','HC6969696','Unstable, BP: 160/100, HR: 70');
Insert into PATIENTS_HEALTH_RECORDS (FIRSTNAME,LASTNAME,HEALTHCARDNUMBER,VITALINFO) values ('Aiden','Williams','HC123000','Stable, BP: 128/78, HR: 75');
Insert into PATIENTS_HEALTH_RECORDS (FIRSTNAME,LASTNAME,HEALTHCARDNUMBER,VITALINFO) values ('Sophia','Johnson','HC789111','Stable, BP: 122/82, HR: 74');
Insert into PATIENTS_HEALTH_RECORDS (FIRSTNAME,LASTNAME,HEALTHCARDNUMBER,VITALINFO) values ('Michael','Brown','HC345222','Stable, BP: 126/78, HR: 70');
Insert into PATIENTS_HEALTH_RECORDS (FIRSTNAME,LASTNAME,HEALTHCARDNUMBER,VITALINFO) values ('Oliver','Smith','HC901333','Stable, BP: 118/76, HR: 72');
Insert into PATIENTS_HEALTH_RECORDS (FIRSTNAME,LASTNAME,HEALTHCARDNUMBER,VITALINFO) values ('Emma','Taylor','HC567444','Stable, BP: 124/80, HR: 75');
Insert into PATIENTS_HEALTH_RECORDS (FIRSTNAME,LASTNAME,HEALTHCARDNUMBER,VITALINFO) values ('Noah','Clark','HC234555','Stable, BP: 122/78, HR: 70');
Insert into PATIENTS_HEALTH_RECORDS (FIRSTNAME,LASTNAME,HEALTHCARDNUMBER,VITALINFO) values ('Ava','Miller','HC890666','Stable, BP: 120/82, HR: 74');
Insert into PATIENTS_HEALTH_RECORDS (FIRSTNAME,LASTNAME,HEALTHCARDNUMBER,VITALINFO) values ('Liam','Anderson','HC456777','Stable, BP: 126/78, HR: 68');
Insert into PATIENTS_HEALTH_RECORDS (FIRSTNAME,LASTNAME,HEALTHCARDNUMBER,VITALINFO) values ('Isabella','Evans','HC012888','Stable, BP: 118/76, HR: 70');
Insert into PATIENTS_HEALTH_RECORDS (FIRSTNAME,LASTNAME,HEALTHCARDNUMBER,VITALINFO) values ('Ethan','Davis','HC678999','Stable, BP: 124/80, HR: 74');
Insert into PATIENTS_HEALTH_RECORDS (FIRSTNAME,LASTNAME,HEALTHCARDNUMBER,VITALINFO) values ('Amelia','Williams','HC6781010','Stable, BP: 122/78, HR: 70');
Insert into PATIENTS_HEALTH_RECORDS (FIRSTNAME,LASTNAME,HEALTHCARDNUMBER,VITALINFO) values ('Harper','Hill','HC1111112','Stable, BP: 126/78, HR: 68');
Insert into PATIENTS_HEALTH_RECORDS (FIRSTNAME,LASTNAME,HEALTHCARDNUMBER,VITALINFO) values ('Charlotte','Martin','HC1212123','Stable, BP: 118/76, HR: 70');
Insert into PATIENTS_HEALTH_RECORDS (FIRSTNAME,LASTNAME,HEALTHCARDNUMBER,VITALINFO) values ('John','Khan','HC1313134','Stable, BP: 124/80, HR: 75');
Insert into PATIENTS_HEALTH_RECORDS (FIRSTNAME,LASTNAME,HEALTHCARDNUMBER,VITALINFO) values ('Sofia','Ghori','HC9362135','Stable, BP: 122/78, HR: 70');
