--------------------------------------------------------
--  File created - Saturday-December-02-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for View PATIENT_MEDICATION_COUNT
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "PATIENT_MEDICATION_COUNT" ("FIRSTNAME", "LASTNAME", "HEALTHCARDNUMBER", "MEDICATIONCOUNT") AS 
  SELECT p.FIRSTNAME, p.LASTNAME, p.HEALTHCARDNUMBER, COUNT(m.MEDICATIONID) AS MedicationCount
FROM PATIENT p
LEFT JOIN HEALTH_RECORD h ON p.HEALTHCARDNUMBER = h.HEALTHCARDNUMBER
LEFT JOIN MEDICATIONS m ON h.HEALTHRECORDID = m.HEALTHRECORDID
GROUP BY p.FIRSTNAME, p.LASTNAME, p.HEALTHCARDNUMBER
;
REM INSERTING into PATIENT_MEDICATION_COUNT
SET DEFINE OFF;
Insert into PATIENT_MEDICATION_COUNT (FIRSTNAME,LASTNAME,HEALTHCARDNUMBER,MEDICATIONCOUNT) values ('Michael','Johnson','HC345678',1);
Insert into PATIENT_MEDICATION_COUNT (FIRSTNAME,LASTNAME,HEALTHCARDNUMBER,MEDICATIONCOUNT) values ('Ethan','Smith','HC222222',0);
Insert into PATIENT_MEDICATION_COUNT (FIRSTNAME,LASTNAME,HEALTHCARDNUMBER,MEDICATIONCOUNT) values ('Isabella','Evans','HC012888',0);
Insert into PATIENT_MEDICATION_COUNT (FIRSTNAME,LASTNAME,HEALTHCARDNUMBER,MEDICATIONCOUNT) values ('Isabella','Johnson','HC111111',0);
Insert into PATIENT_MEDICATION_COUNT (FIRSTNAME,LASTNAME,HEALTHCARDNUMBER,MEDICATIONCOUNT) values ('Sarah','Williams','HC901234',1);
Insert into PATIENT_MEDICATION_COUNT (FIRSTNAME,LASTNAME,HEALTHCARDNUMBER,MEDICATIONCOUNT) values ('Daniel','Davis','HC012345',1);
Insert into PATIENT_MEDICATION_COUNT (FIRSTNAME,LASTNAME,HEALTHCARDNUMBER,MEDICATIONCOUNT) values ('Ava','Clark','HC678901',1);
Insert into PATIENT_MEDICATION_COUNT (FIRSTNAME,LASTNAME,HEALTHCARDNUMBER,MEDICATIONCOUNT) values ('Mia','Brown','HC999999',0);
Insert into PATIENT_MEDICATION_COUNT (FIRSTNAME,LASTNAME,HEALTHCARDNUMBER,MEDICATIONCOUNT) values ('Harper','Martin','HC1313131',0);
Insert into PATIENT_MEDICATION_COUNT (FIRSTNAME,LASTNAME,HEALTHCARDNUMBER,MEDICATIONCOUNT) values ('James','Miller','HC890123',1);
Insert into PATIENT_MEDICATION_COUNT (FIRSTNAME,LASTNAME,HEALTHCARDNUMBER,MEDICATIONCOUNT) values ('Aiden','Williams','HC123000',1);
Insert into PATIENT_MEDICATION_COUNT (FIRSTNAME,LASTNAME,HEALTHCARDNUMBER,MEDICATIONCOUNT) values ('Ahraz','Beautiful','HC936254',0);
Insert into PATIENT_MEDICATION_COUNT (FIRSTNAME,LASTNAME,HEALTHCARDNUMBER,MEDICATIONCOUNT) values ('Ethan','Davis','HC678999',0);
Insert into PATIENT_MEDICATION_COUNT (FIRSTNAME,LASTNAME,HEALTHCARDNUMBER,MEDICATIONCOUNT) values ('Sophia','Miller','HC777777',0);
Insert into PATIENT_MEDICATION_COUNT (FIRSTNAME,LASTNAME,HEALTHCARDNUMBER,MEDICATIONCOUNT) values ('Noah','Davis','HC666666',0);
Insert into PATIENT_MEDICATION_COUNT (FIRSTNAME,LASTNAME,HEALTHCARDNUMBER,MEDICATIONCOUNT) values ('Amelia','Clark','HC1212121',0);
Insert into PATIENT_MEDICATION_COUNT (FIRSTNAME,LASTNAME,HEALTHCARDNUMBER,MEDICATIONCOUNT) values ('Sofia','Ghori','HC9362135',0);
Insert into PATIENT_MEDICATION_COUNT (FIRSTNAME,LASTNAME,HEALTHCARDNUMBER,MEDICATIONCOUNT) values ('Liam','Williams','HC444444',0);
Insert into PATIENT_MEDICATION_COUNT (FIRSTNAME,LASTNAME,HEALTHCARDNUMBER,MEDICATIONCOUNT) values ('John','Doe','HC123456',1);
Insert into PATIENT_MEDICATION_COUNT (FIRSTNAME,LASTNAME,HEALTHCARDNUMBER,MEDICATIONCOUNT) values ('Emma','Taylor','HC567444',1);
Insert into PATIENT_MEDICATION_COUNT (FIRSTNAME,LASTNAME,HEALTHCARDNUMBER,MEDICATIONCOUNT) values ('Liam','Anderson','HC456777',1);
Insert into PATIENT_MEDICATION_COUNT (FIRSTNAME,LASTNAME,HEALTHCARDNUMBER,MEDICATIONCOUNT) values ('Ahraz','Kibria','HC678111',0);
Insert into PATIENT_MEDICATION_COUNT (FIRSTNAME,LASTNAME,HEALTHCARDNUMBER,MEDICATIONCOUNT) values ('Jane','Smith','HC789012',1);
Insert into PATIENT_MEDICATION_COUNT (FIRSTNAME,LASTNAME,HEALTHCARDNUMBER,MEDICATIONCOUNT) values ('Oliver','Smith','HC901333',1);
Insert into PATIENT_MEDICATION_COUNT (FIRSTNAME,LASTNAME,HEALTHCARDNUMBER,MEDICATIONCOUNT) values ('Oliver','Hill','HC1111110',0);
Insert into PATIENT_MEDICATION_COUNT (FIRSTNAME,LASTNAME,HEALTHCARDNUMBER,MEDICATIONCOUNT) values ('Charlotte','Evans','HC101010',0);
Insert into PATIENT_MEDICATION_COUNT (FIRSTNAME,LASTNAME,HEALTHCARDNUMBER,MEDICATIONCOUNT) values ('Sophia','Johnson','HC789111',1);
Insert into PATIENT_MEDICATION_COUNT (FIRSTNAME,LASTNAME,HEALTHCARDNUMBER,MEDICATIONCOUNT) values ('Noah','Clark','HC234555',1);
Insert into PATIENT_MEDICATION_COUNT (FIRSTNAME,LASTNAME,HEALTHCARDNUMBER,MEDICATIONCOUNT) values ('Ava','Miller','HC890666',1);
Insert into PATIENT_MEDICATION_COUNT (FIRSTNAME,LASTNAME,HEALTHCARDNUMBER,MEDICATIONCOUNT) values ('Charlotte','Martin','HC1212123',0);
Insert into PATIENT_MEDICATION_COUNT (FIRSTNAME,LASTNAME,HEALTHCARDNUMBER,MEDICATIONCOUNT) values ('Ava','Jones','HC555555',0);
Insert into PATIENT_MEDICATION_COUNT (FIRSTNAME,LASTNAME,HEALTHCARDNUMBER,MEDICATIONCOUNT) values ('Sarah','Khan','HC9362136',0);
Insert into PATIENT_MEDICATION_COUNT (FIRSTNAME,LASTNAME,HEALTHCARDNUMBER,MEDICATIONCOUNT) values ('Taha','Ghori','HC6969696',0);
Insert into PATIENT_MEDICATION_COUNT (FIRSTNAME,LASTNAME,HEALTHCARDNUMBER,MEDICATIONCOUNT) values ('Logan','Taylor','HC888888',0);
Insert into PATIENT_MEDICATION_COUNT (FIRSTNAME,LASTNAME,HEALTHCARDNUMBER,MEDICATIONCOUNT) values ('David','Brown','HC567890',1);
Insert into PATIENT_MEDICATION_COUNT (FIRSTNAME,LASTNAME,HEALTHCARDNUMBER,MEDICATIONCOUNT) values ('Emily','Taylor','HC234567',1);
Insert into PATIENT_MEDICATION_COUNT (FIRSTNAME,LASTNAME,HEALTHCARDNUMBER,MEDICATIONCOUNT) values ('Olivia','Anderson','HC456789',1);
Insert into PATIENT_MEDICATION_COUNT (FIRSTNAME,LASTNAME,HEALTHCARDNUMBER,MEDICATIONCOUNT) values ('Michael','Brown','HC345222',1);
Insert into PATIENT_MEDICATION_COUNT (FIRSTNAME,LASTNAME,HEALTHCARDNUMBER,MEDICATIONCOUNT) values ('Olivia','Anderson','HC333333',0);
Insert into PATIENT_MEDICATION_COUNT (FIRSTNAME,LASTNAME,HEALTHCARDNUMBER,MEDICATIONCOUNT) values ('Harper','Hill','HC1111112',0);
Insert into PATIENT_MEDICATION_COUNT (FIRSTNAME,LASTNAME,HEALTHCARDNUMBER,MEDICATIONCOUNT) values ('Amelia','Williams','HC6781010',0);
Insert into PATIENT_MEDICATION_COUNT (FIRSTNAME,LASTNAME,HEALTHCARDNUMBER,MEDICATIONCOUNT) values ('John','Khan','HC1313134',0);
